export const ApiRoutes = {
  baseURI: "http://localhost:5500/",
  Personas: "Personas/",
  TipoEntidad: "tipoEntidad/",
  TipoBarrio: "tipoBarrio/",
  Area: "area/",
  Barrios: "barrios/",
  Ruta: "ruta/",
  TipoVivienda: "tipoVivienda/",
  ActividadEconomica: "actividadEconomica/",
  Entidad: "entidad/",
  Familia: "familia/",
  HistorialMedico: "historialMedico/",
  Persona: "persona/",
  PersonaAdulta: "personaAdulta/",
  PersonaJoven: "personaJoven/",
  PersonaMenor: "personaMenor/",
  TipoEducacion: "tipoEducacion/",
  TipoPersona: "tipoPersona/",
};
